controllers:
    resource: ../src/Controller/
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\MainPageController::index

admin_controller_add:
    path: /admin/add
    controller: App\Controller\AdminController::add
    methods: POST

exercise_index:
    path: /exercise
    controller: App\Controller\ExerciseController::index
    methods: GET

exercise_add:
    path: /exercise/add
    controller: App\Controller\ExerciseController::add
    methods: [GET, POST]

exercise_edit:
    path: /exercise/{id}/edit
    controller: App\Controller\ExerciseController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

exercise_delete:
    path: /exercise/{id}/delete
    controller: App\Controller\ExerciseController::delete
    methods: [GET, POST]
    requirements:
        id: '\d+'

exercise_list:       
    path: /exercise/list
    controller: App\Controller\ExerciseController::list
    methods: GET


profile:
    path: /profile
    controller: App\Controller\ProfileController::profile
    methods: GET

calculate_diet_plan:
    path: /user/calculate_diet_plan
    controller: App\Controller\UserController::calculateDietPlan
    methods: [GET, POST]

add_to_database:
    path: /user/add_to_database
    controller: App\Controller\UserController::addToDatabase
    methods: [GET, POST]

weight_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'
weight_delete:
    path: /user/{id}/delete
    controller: App\Controller\UserController::delete
    methods: [GET, POST]
    requirements:
        id: '\d+'
weight_list:       
    path: /user/list
    controller: App\Controller\UserController::list
    methods: GET