controllers:
    resource: ../src/Controller/
    type: attribute
app_homepage:
    path: /
    controller: App\Controller\MainPageController::index
#-----------EXERCISE--------
exercise_index:
    path: /exercise
    controller: App\Controller\ExerciseController::index
    methods: GET

exercise_add:
    path: /exercise/add
    controller: App\Controller\ExerciseController::add
    methods: [GET, POST]

exercise_edit:
    path: /exercise/{id}/edit
    controller: App\Controller\ExerciseController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

exercise_delete:
    path: /exercise/{id}/delete
    controller: App\Controller\ExerciseController::delete
    methods: [GET, POST]
    requirements:
        id: '\d+'

exercise_list:       
    path: /exercise/list
    controller: App\Controller\ExerciseController::list
    methods: GET

#---------DIET PLAN--------
profile:
    path: /profile
    controller: App\Controller\ProfileController::profile
    methods: GET

calculate_diet_plan:
    path: /user/calculate_diet_plan
    controller: App\Controller\UserController::calculateDietPlan
    methods: [GET, POST]
app_meal_plan:
    path: /user/plan
    controller: App\Controller\UserController::userFoodPage
    methods: [GET, POST]

add_to_database:
    path: /user/add_to_database
    controller: App\Controller\UserController::addToDatabase
    methods: [GET, POST]

weight_edit:
    path: /user/{id}/edit
    methods: [GET, POST]
    requirements:
        id: '\d+'
    defaults:
        _controller: 'App\Controller\UserController::edit'
        _converters:
            dietPlan: 'doctrine.orm:App\Entity\DietPlanDatabase(dietPlanDatabase)'
weight_delete:
    path: /user/{id}/delete
    controller: App\Controller\UserController::delete
    methods: [GET, POST]
    requirements:
        id: '\d+'
weight_list:       
    path: /user/list
    controller: App\Controller\UserController::list
    methods: GET
    
# -------------------MEAL-----------
meal_index:
    path: /meal
    controller: App\Controller\MealController::index
    methods: GET

meal_create:
    path: /meal/add
    controller: App\Controller\MealController::add
    methods: [GET, POST]

meal_edit:
    path: /meal/{id}/edit
    controller: App\Controller\MealController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

meal_delete:
    path: /meal/{id}/delete
    controller: App\Controller\MealController::delete
    methods: GET
    requirements:
        id: '\d+'
meal_list:       
    path: /meal/list
    controller: App\Controller\MealController::list
    methods: GET

# ------------------YOGA-----------
yoga_controller:
    path: /yoga/{exerciseId}
    controller: App\Controller\YogaController::index
    methods: GET
    requirements:
        exerciseId: \d+
# ------------------USER MEAL FOOD-----------
add_meal_to_user_food:
  path: /add-meal-to-user-food
  controller: App\Controller\UserController::addMealToUserFood
  methods: [POST]
